name: dev

on:
  push:
    branches:
    - dev

jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps: 
    - name: "checkout"
      uses: actions/checkout@master

    - name: Setting up node
      uses: actions/setup-node@master
      with:
        node-version: '14.x'

    - name: Installing runner dependencies
      run: npm i
    
    - name: "Building"
      run: npm run build --if-present

    - name: "Testing"
      run: npm test --if-present

    - name: "Copying files to remote"
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "public,server/dist,server/res,replServer/dist,replServer/res"
        target: /var/www/html/reactive/dev
        tar_tmp_path: true

    

  dependencies: 
    runs-on: ubuntu-latest

    
    steps: 
    - name: 
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "package.json,./.deploy"
        target: /var/www/html/reactive/dev
        tar_tmp_path: true

    - name: "Installing dependencies on remote"
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd /var/www/html/reactive/dev
          source ~/.nvm/nvm.sh
          nvm use 14.0.0
          npm i

  deploy: 
    runs-on: ubuntu-latest
    needs: [build, dependencies]

    steps:
    - name: "Installing dependencies on remote"
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd /var/www/html/reactive/dev
          source ~/.nvm/nvm.sh
          nvm use 14.0.0
          wait-on ecosystem.config.js
          node pm2Reload.js

